version: "3.8"

services:
  blockscout:
    image: moacdev/blockscout:4.0.0
    container_name: blockscout
    restart: "no"
    environment:
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@blockscoutpostgres/postgres?ssl=false
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - NETWORK=quickstart
      - NETWORK=Dev Quickstart
      - SUBNETWORK=Quorum
      - CHAIN_ID=10
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_TRANSPORT=http
      - ETHEREUM_JSONRPC_HTTP_URL=http://44.203.77.91:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://44.203.77.91:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://44.203.77.91:8546
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /opt/app/;
        echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
    depends_on:
      - blockscoutpostgres
    links:
      - blockscoutpostgres
    ports:
      - 4000:4000

  blockscoutpostgres:
    image: postgres:13.4-alpine
    restart: "on-failure"
    container_name: blockscoutpostgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
